version: "3"
services:
  central-db:
    image: postgres
    environment:
      POSTGRES_USER: bharathraj
      POSTGRES_PASSWORD: yesitsme
      POSTGRES_DB: tokka-labs-db
    ports:
      - "5434:5432"
    volumes:
      - ./database-service/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bharathraj -d tokka-labs-db"]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - common-network

  backend-db-migration:
    build:
      context: ./backendSystem
      dockerfile: Dockerfile.migration
    depends_on:
      central-db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://bharathraj:yesitsme@central-db:5432/tokka-labs-db?schema=public"
    networks:
      - common-network

  backend-server:
    build:
      context: ./backendSystem
      args:
        - no_cache=1
    depends_on:
      - central-db
      - redis
    ports:
      - "3003:3000"
    environment:
      DB_HOST: central-db
      DB_USER: bharathraj
      DB_PASSWORD: yesitsme
      DB_NAME: tokka-labs-db
      DB_PORT: 5432
      DATABASE_URL: "postgresql://bharathraj:yesitsme@central-db:5432/tokka-labs-db?schema=public"
      NODE_ENV: docker
      REDIS_PORT: 6379
      REDIS_HOST: redis
      SERVER_PORT: 3000
    networks:
      - common-network

  # price-feeder-server:
  #   build:
  #     context: ./externalPriceFeeder
  #     args:
  #       - no_cache=1
  #   ports:
  #     - "3004:3000"
  #   environment:
  #     DB_HOST: central-db
  #     DB_USER: bharathraj
  #     DB_PASSWORD: yesitsme
  #     DB_NAME: tokka-labs-db
  #     DB_PORT: 5432
  #     DATABASE_URL: "postgresql://bharathraj:yesitsme@central-db:5432/tokka-labs-db?schema=public"
  #     NODE_ENV: docker
  #     SERVER_PORT: 3000
  #   networks:
  #     - common-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - common-network

  prisma-studio:
    build:
      context: ./backendSystem
      dockerfile: Dockerfile.prismaStudio
    depends_on:
      central-db:
        condition: service_healthy
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://bharathraj:yesitsme@central-db:5432/tokka-labs-db?schema=public"
    networks:
      - common-network

networks:
  common-network:

volumes:
  pgdata:
